# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_myhome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhome',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
