# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20161018_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhome',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='myhome',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
